### ISSUE TITLE
Reject all but necessary

### ISSUE THREAD

**Issue by michalbulla** [elleracompany/craft-cookie-consent#104]
Hi there, 

If my information are correct, in EU it is shown by law to have the Reject All button displayed, so the customer can reject all but necessary cookies by one click. 

Is this possible ?

Thanks

**Comment by jellingsen** [comment]
Hi,

This should be possible by modifying the template, but we should add it in the example template - and probably a function to handle it in the endpoints.

**Comment by lexislav** [comment]
Hi,
I have solved this by adding a decline all button into the template and modifying default script by adding this code on line 60:
```let declineAllLinks = document.getElementById("elc-decline-link");
    if (declineAllLinks !== null) {
        if (declineAllLinks.addEventListener) {
            console.log('hooked');
            declineAllsLink.addEventListener("click", submitConsent);
        } else if (declineAllLink.attachEvent) {
            declineAllsLink.attachEvent("onclick", submitConsent);
        }
    }````
