### ISSUE TITLE
Javascript error form.dataset.show undefined 

### ISSUE THREAD

**Issue by gizmothecat** [elleracompany/craft-cookie-consent#109]
Trying the plugin for the first time on a craft 5 install and it doesn't display the default bottom modal as expected.
I never tried the plugin before and I tried it on a craft 4 install and it works as expected.

I get that javascript error :
<img width="598" alt="Screenshot 2024-04-24 at 21 13 06" src="https://github.com/elleracompany/craft-cookie-consent/assets/1843711/9aa85b3a-002f-4350-a1ce-6bf52f19ae4d">

Any ideas?

Thanks

**Comment by jellingsen** [comment]
Hi @gizmothecat 

I'm unable to reproduce. Are you using a custom template for the banner?

**Comment by gizmothecat** [comment]
I have been able to resolve the problem. But I have found an Yii error when you delete a cookie group it sends you to a page that doesn't exist.

**Comment by jellingsen** [comment]
Thank you for reporting it.
Redirect after cookie group deletion now fixed.

**Comment by mathieuser** [comment]
I'm getting this form.dataset.show undefined in a Craft 4 set-up... Not really knowing what to do with it. @gizmothecat how did you resolve this? Thanks!
