### ISSUE TITLE
Safari window.onload delay causing submitConsent event listener issue

### ISSUE THREAD

**Issue by jonXmack** [elleracompany/craft-cookie-consent#11]
We have had an issue with a client of ours who is using this plugin. Their homepage has a video banner on it, and it turns out that despite the progress bar showing the page as fully loaded in Safari, it doesn't fire the `window.onload` event until the video is downloaded too. This meant that if you hit the OK button before Safari triggered the `onload` event - and thus added the `submitConsent` event listener - then it would redirect you to a blank page with nothing but the `true` response on.

To mitigate this I have set the banner to be hidden by default, and then I'm using js to check for the `cookie-consent` cookie, and if this doesn't exist, then remove the hidden class once the `window.onload` function fires. This appears to be working for us, but I just wanted to make you aware of the strange nuance of Safari.

**Comment by jellingsen** [comment]
Thank you for letting us know. We'll have a look at it.

**Comment by jellingsen** [comment]
The PR from @NRauh should have fixed this @jonXmack, so I'm closing this issue.
Should this issue still exist please reopen the issue.
