### ISSUE TITLE
Permissions for creating a cookie group are not in effect

### ISSUE THREAD

**Issue by thomas-jaeger** [elleracompany/craft-cookie-consent#112]
I received the following exception:
```
2024-07-17 13:49:47 [web.ERROR] [yii\web\HttpException:403] User is not authorized to perform this action. 
{
    "trace": [
        "#0 /app/vendor/elleracompany/craft-cookie-consent/src/controllers/SettingsController.php(218): craft\\web\\Controller->requirePermission('cookie-consent:...')",

```
when trying to add a new cookie group, even though I have permission to do so.

Looking into the code, Settings-Controller.php Line 218 checks:
- `$this->requirePermission('cookie-consent:cookie-groups:create');`
but if i configure the permission "Create new Cookie Group" for a group, the group will get the
- `cookie-consent:cookie-groups:create-new`
permission in its configuration.

Line 218 in the SettingsController.php seems to be incorrect; it is likely missing '-new'.

**Comment by jellingsen** [comment]
Fixed in v5.0.2
