### ISSUE TITLE
Errors running on Postgres database

### ISSUE THREAD

**Issue by bartroelands** [elleracompany/craft-cookie-consent#13]
Hi, 

I recently moved my production site to a postgres backend ... I noticed that the default cookie group and  examples were not loaded during install. When creating a new group I got server errors. Looking at the logs and the code the script fails in the settings controller in the function actionSaveCookieGroup()

`$record = CookieGroup::findOne([
			'id' => Craft::$app->request->post('id')
		]);`

The post request returns an empty string which postgres cannot handle as an int value it seems.

`Array
(
    [0] => 22P02
    [1] => 7
    [2] => ERROR:  invalid input syntax for integer: ""
)`

I tried to debug a bit forcing the empty string to be casted to an integer, but got further up into other issues. I would expect that when I create a new group the group id would be already populated in the hidden groupid field in the group.twig template. Now the field is empty?? It seems that the logic is expecting to have a number of records to be available in the database from the start.

Can you look in to this? 

Thank you

Bart

**Comment by jellingsen** [comment]
Hi Bart,

The `id`-field of cookie groups was declared in fields() which resulted in it being populated with an empty string. MySQL handles this, but postgres does not. This should now be fixed in Release v1.2.6.

Hopefully this fixes your issues, if not, do not hesitate to create a new issue.
