### ISSUE TITLE
Pop Up Shows Every Time After Upgrade

### ISSUE THREAD

**Issue by enobis-dev** [elleracompany/craft-cookie-consent#14]
Hello:
I have a client that we are using this plugin on and just updated this weekend as there were some small quirks that we were hoping the update would fix, but we seem to have a bigger issue since the upgrade...

When we click the "OK" button the pop up will disappear as expected, but going to a new page the pop up reappears, and this goes on and on.

A couple of items to note:
- we are using our own template, but double checked the default one sent and see that our OK button still matches the ones in your default template.
- we can run this on our development server successfully, using an IP address in the URL instead of a domain name, we don't experience this issue, it works as expected
- we are running a multi site set up and this is a persistent issue across all of the sites.

Thanks!

**Comment by jellingsen** [comment]
Hi,

I was able to reproduce an issue when the "Show after Consent" setting was toggled off. But this could not have worked on your development server, and I find that interesting.
I published a fix for that issue with release 1.2.7.

Could you please provide me with some more information:
- Do you get any output/errors in the browser console when consent is given?
- Is the consent registered in the administration panel (/admin/cookie-consent/site/<site_slug>/consent)?
- Do you have any asset caching on your production server?

**Comment by enobis-dev** [comment]
Yes, we get an error when loading the page:
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.<anonymous> (script.js?v=1580229045:28)
```
Verified that it is your Javascript, line 28:
`if (tabLink.addEventListener) {`

and, get an error when clicking "OK":
```
Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLFormElement.submitConsent (script.js?v=1580229045:43)
```
in your Javascript file:
`document.getElementById("elc-cookie-tab").classList.toggle('elc-hidden');`

Consent is registered, but the "Show after Consent" was off - I toggled it on and the little "cookie" button appeared as expected in all the pages, but not the pop up.  Then I went back and toggled it back off and then never saw the pop up on any of the pages after that.  I then removed the consent cookie from the browser to check and the same problem still continued with the "Show after Consent" off.

I cleared all caches before running these tests and ran them only on the production server. 

Thanks!

**Comment by enobis-dev** [comment]
Ugh...  Nevermind, it's working now.

We weren't on version 1.2.7 even though we had just run the system updates yesterday, however, Craft hadn't indicated that their were any additional updates available either until after I cleared all the caches and then there it was.  This seems to be working correctly in the 1.2.7 version, my apologies.

Many thanks for the prompt response and the plugin.  We will run more tests and checks and I'll let you know if we see anything, but for now, this is working.

**Comment by jellingsen** [comment]
Glad to hear!
Thank you for bringing the issue to our attention.

Ill close this issue, but feel free to reopen or create a new issue should you experience any problems.
