### ISSUE TITLE
Default Consent Settings (enhancement)

### ISSUE THREAD

**Issue by kerns** [elleracompany/craft-cookie-consent#19]
Maybe I misunderstand something, but per definition ..for true GDPR compliance I don't believe there can be any no non-essential groups selected by default? Small detail, but if that is indeed the case I would revisit this default config for statistics after installation.

<img width="698" alt="Screen Shot 2020-05-17 at 15 55 08" src="https://user-images.githubusercontent.com/20254/82149514-3d862680-9857-11ea-9fb1-25275267dbcc.png">

**Comment by jellingsen** [comment]
Hi,

When we created the plugin this seemed to be the industry standard. Revisiting this topic now it seems like the industry has shifted towards a solution where only the essential groups are selected by default, but a brightly colored button named "Accept all" and a small/less visible button named "save settings" are present. 

This way, 99% of visitors will click "Accept all" and all the cookie groups will be selected.

I think we'll update the default settings, but also provide options for activating a "Accept all" type button.

**Comment by jellingsen** [comment]
This is now updated in v1.3.0

**Comment by kerns** [comment]
Ah – hmmm. I didn't see this before filing my last issue (which was really a question) :-)

So did you update to the model I described there... I think the industry refers to it as "implied consent". Green button to accept all, but a settings/details button that shows all groups (and respects defaults as set by the administrator)
