### ISSUE TITLE
Wrong URl of plugin admin pages if Craft is installed in subfolder

### ISSUE THREAD

**Issue by piotrpog** [elleracompany/craft-cookie-consent#2]
If craft is not installed directly under some domain but in subfolder, URl of admin pages of plugin is wrong. For example:

Instead of this `http://domain.com.pl/directory/web/admin/cookie-consent/site/default` we get this `http://domain.com.pl/admin/cookie-consent/site/default`.

**Comment by geoffreyvandamme** [comment]
Any news on this? experiencing the same problem, also the pop-up throws a 404 error when i hit the 'OK' button, probably also because it posts to the root folder, and not the /web

**Comment by jellingsen** [comment]
@piotrpog and @geoffreyvandamme sorry for the delay over the summer. We'll look into this next week.

**Comment by jellingsen** [comment]
This issue is now fixed and will be shipped with v1.2 in the beginning of next week.
