### ISSUE TITLE
Question RE: Flow of Cookie Consent...

### ISSUE THREAD

**Issue by kerns** [elleracompany/craft-cookie-consent#23]
Does ccc operate with the "implied permission" model? – that is to say, users can accept all cookies in one click, ...but if they wish, they can also review details. At which point all groups are displayed and none (but the essential) groups are activated by default.

Maybe it works this way already when the "show options" (the toggles) are disabled? Here is layout I am working with to better illustrate...

<img width="1019" alt="Screen Shot 2020-05-23 at 20 50 45" src="https://user-images.githubusercontent.com/20254/82738422-b396fb80-9d37-11ea-8654-a736721996de.png">

**Comment by jellingsen** [comment]
Yes, this is now possible. You would get a similar solution by enabling the "accept all" button and disable checkboxes until the box is expanded. You're able to implement your own design by utilizing the endpoints and looking at the default banner.twig
