### ISSUE TITLE
Better Post-Accept Handling of "Edit Preferences" Link (elc-cookie-tab)

### ISSUE THREAD

**Issue by kerns** [elleracompany/craft-cookie-consent#24]
Once a user has granted (or not) their initial consent, the link to revisit or edit preferences (elc-cookie-tab) should (I feel) fire the expanded panel, instead of just re-initiating the initial consent dialog...which is not as relevant and could also be confusing.

**Comment by jellingsen** [comment]
The banner should now open ull to full-size when revisiting your consent.
