### ISSUE TITLE
Widget or page to show statistics of consents

### ISSUE THREAD

**Issue by kringkaste** [elleracompany/craft-cookie-consent#27]
Our customer wants to have a simple statistics of the consents. I think a widget would be nice, just a donut chart of all consents of one or all sites by their groups. If we implement this, would you be willing to accept a pull request for this?

**Comment by jellingsen** [comment]
Great idea. If you want to make a PR, please do!

**Comment by jellingsen** [comment]
No need to have this issue open. Please consider making a PR, if not we might create this functionality ourselves.
