### ISSUE TITLE
Renaming/Re-ordering of Groups

### ISSUE THREAD

**Issue by kerns** [elleracompany/craft-cookie-consent#28]
It seems like once a group is created the slug cannot be renamed and the group cannot be re-ordered. When neither is possible it really demands that you get your groups correct the first time and never want/need to change them.

I have twice now needed to destroy all groups and entries within each group in order to address either the order or name of a group. I can anticipate needing to do this again in the future.

**Comment by jellingsen** [comment]
Yeah. This is a good idea. I will look into a solution for this

**Comment by jellingsen** [comment]
Added a working solution with a order field on each group. This is not a beautiful solution, but it should solve the issue for now.
