### ISSUE TITLE
cookies table displaying empty rows in CP

### ISSUE THREAD

**Issue by pieter-janDB** [elleracompany/craft-cookie-consent#34]
Hi again, this issue described here has returned in 1.3.1 : https://github.com/elleracompany/craft-cookie-consent/issues/16

The 'cookie_consent_group' table shows all my groups with their content but the frontend CP (So for example: http://mysite.com/craft/cookie-consent/group/default/1) shows empty tables again (an empty row for every cookie I had there before). Basically the very same as before.

I opened a new issue because I am unsure if you get notified for closed issues.

Thanks in advance.

**Comment by jellingsen** [comment]
Will continue this in #16
