### ISSUE TITLE
Twig Runtime Error After Upgrade...

### ISSUE THREAD

**Issue by kerns** [elleracompany/craft-cookie-consent#35]
<img width="894" alt="Screen Shot 2020-06-10 at 12 26 02" src="https://user-images.githubusercontent.com/20254/84257479-ab033b00-ab15-11ea-9e3c-4ad9df651561.png">

Error after latest update when trying to view consents from the cp...  🤔

**Comment by jellingsen** [comment]
Hi,

I was able to reproduce, but this is not related to the update, but rather an existing bug when you create new cookie groups and have consents stored without that cookie group already. 

I'll provide an update.

**Comment by jellingsen** [comment]
Can you give 1.4.1 a try?
