### ISSUE TITLE
column "refresh" is of type integer but default expression is of type boolean

### ISSUE THREAD

**Issue by nflorentin** [elleracompany/craft-cookie-consent#40]
Hi,

Trying to update to 1.4.2, I have the following error:
```
Database Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column “refresh” is of type integer but default expression is of type boolean
HINT: You will need to rewrite or cast the expression.
The SQL being executed was: ALTER TABLE “cookie_consent_site_settings” ADD “refresh” integer NOT NULL DEFAULT FALSE
```

I'm not sure but I think that the type of the column "refresh" should be boolean and not integer.

Thanks for your work on this plugin !

**Comment by jellingsen** [comment]
Hi, ill have a look at this tomorrow. What database are you using?

**Comment by nflorentin** [comment]
Wow, you're ultra reactive!

I'm using PostgreSQL 11.3. 

As I can see in Yii documentation, there is a method to create boolean column: https://www.yiiframework.com/doc/api/2.0/yii-db-schemabuildertrait#boolean()-detail

**Comment by jellingsen** [comment]
This should now work on v1.4.3. I've tested with postgres 12.1.
