### ISSUE TITLE
Cache busting with SEOmatic

### ISSUE THREAD

**Issue by damienbuckley** [elleracompany/craft-cookie-consent#46]
Hi, not an issue - just not sure whether the below cache busting code is required when using with SEOmatic ongoing or only once - i.e. when first installed?

`{# -- START Cache-bust seomatic -- #}
{% set scriptContainer = seomatic.script.container() %}
{% do scriptContainer.clearCache(true) %}
{# -- END Cache-bust seomatic -- #}`

**Comment by jellingsen** [comment]
This would be required to be there as long as the cookie consent banner and SEOmatic both installed together.

**Comment by damienbuckley** [comment]
Thanks. Do I still need the hook if using SEOmatic? 

`{% hook 'before-body-end' %}`

And if so, does it matter in which order they are placed?

**Comment by jellingsen** [comment]
Hi,

Yes, you still need the hook. The order should not matter.
