### ISSUE TITLE
Statics page caching (Blitz)

### ISSUE THREAD

**Issue by umkasanki** [elleracompany/craft-cookie-consent#47]
Is it posible to configure your plugin to use with Blitz?
Now then I click on "Allow all" button I get an error 400 (Unable to verify your data submission.)
Thanks.

**Comment by NickLanger1990** [comment]
Hey!
Got the same issue. Is there a quick solution?
best

**Comment by umkasanki** [comment]
> 
> 
> Hey!
> Got the same issue. Is there a quick solution?
> best

https://github.com/elleracompany/craft-cookie-consent/issues/18

**Comment by jellingsen** [comment]
Hi.

Have a look at the solution [here](https://github.com/elleracompany/craft-cookie-consent/issues/30) and see if that helps you. I'll work on getting it into the README
