### ISSUE TITLE
Implementation issues

### ISSUE THREAD

**Issue by darylknight** [elleracompany/craft-cookie-consent#5]
Hi guys,

Great job on putting this together - I've been looking for a decent solution that doesn't involve a subscription and the plugin makes great sense. That being said, I'm struggling to implement it correctly (using it on my own site before I try it with a client). Hopefully if I give you all the info you can point me in the direction of what's going wrong?

**Config**
![image](https://user-images.githubusercontent.com/1250017/63589373-9c14c180-c5b1-11e9-918f-ed626370c291.png)

**Statistics screen**
![image](https://user-images.githubusercontent.com/1250017/63589597-3f65d680-c5b2-11e9-8344-910e9ff57fd5.png)

**SEOmatic script**

    {% if craft.cookieConsent.getConsent('default-statistics') == 1 %}
        console.log("{{ craft.cookieConsent.getConsent('default-statistics') }}");
        {% if trackingId.value is defined and trackingId.value %}
            console.log('tracking started');
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','{{ analyticsUrl.value }}','ga');
            ga('create', '{{ trackingId.value |raw }}', 'auto'{% if linker.value %}, {allowLinker: true}{% endif %});
            {% if ipAnonymization.value or craft.cookieConsent.getConsent('default-marketing') != true %}ga('set', 'anonymizeIp', true);{% endif %}
            {% if displayFeatures.value and craft.cookieConsent.getConsent('default-marketing') %}ga('require', 'displayfeatures');{% endif %}
            {% if ecommerce.value and craft.cookieConsent.getConsent('default-marketing') %}ga('require', 'ecommerce');{% endif %}
            {% if enhancedEcommerce.value and craft.cookieConsent.getConsent('default-marketing') %}ga('require', 'ec');{% endif %}
            {% if enhancedLinkAttribution.value and craft.cookieConsent.getConsent('default-marketing') %}ga('require', 'linkid');{% endif %}
            {% if enhancedLinkAttribution.value and craft.cookieConsent.getConsent('default-marketing') %}ga('require', 'linker');{% endif %}
            {% set pageView = (sendPageView.value and not craft.app.request.isLivePreview) %}
            {% if pageView %}ga('send', 'pageview');{% endif %}
        {% endif %}
    {% else %}
        console.log('permission not given, do not track'); 
    {% endif %}

Basically that should be saying "if consent to default-statistics is given, load the GA scripts. If permission to default-marketing is given, load the individual plugins. If you look at codeknight.co.uk with the console log open, you'll see that if you allow all categories, then click ok, nothing happens (I think this is expected). Also:

- Go to another page and the console logs `1` and `tracking started`.
- Go back to the page you were on, and it's back to "permission not given, do not track"
- Removing permissions, clicking ok then refreshing the page STILL records permission as being given, and shows `1` and `tracking started`. I know you need to manually delete third party cookies, but it shouldn't be detecting that permission has been given if it's been revoked.

After adding and removing permissions for a while, I'm now getting the following results on the main pages of my site regardless of what options are chosen:

- Home: No permissions, don't track
- About: Permission given. Start analytics tracking
- Blog: Permission given. Start analytics tracking
- Testimonials: Permission given. Start analytics tracking
- Work: No permissions, don't track
- Contact: No permissions, don't track

I'm not using cache tags anywhere around this plugin. Any idea what's causing totally inconsistent results?

**Comment by jellingsen** [comment]
I'm getting the same results as you on your page. I've so far been unable to reproduce on my local installation using your javascript. I'm toggling statistics on and off and the console log behaves as expected.

I'll investigate further and let you know. Please let me know if you find anything.

**Comment by jellingsen** [comment]
After some more investigation it seems the functions from the plugin is not reachable within SEOmatic's script renderer. I'll look into it and see if we can provide a patch fast.

**Comment by khalwat** [comment]
SEOmatic caches the containers after they are rendered, that includes the Script containers. If you want dynamic conditionals, you'd need to bust the cache manually via  ```twig
{% set scriptContainer = seomatic.script.container() %}
{% do scriptContainer.clearCache(true) %}
```
