### ISSUE TITLE
Is this compatible with Craft 3.5?

### ISSUE THREAD

**Issue by hugo-costa** [elleracompany/craft-cookie-consent#53]
Hi,

I have followed the instructions, however I do not see any errors but also no cookie consent on the front end. Just wanted to know if its compatible with Craft 3.5?

**Comment by peteralewis** [comment]
Hi, I'm on 3.5.14 and it's running fine. I assume it could be an issue with your setup if it's not appearing...?

**Comment by jellingsen** [comment]
Yes, the plugin works with 3.5. If you have any issues please read the documentation carefully and open a new issue should you still have problems.
