### ISSUE TITLE
Invalidate current cookie consent...?

### ISSUE THREAD

**Issue by peteralewis** [elleracompany/craft-cookie-consent#54]
Any suggestions on how to invalidate the current consent?

I've added a new cookie group, so all existing consent doesn't include this, so before I can get the new group to trigger for existing consentors, I need to invalidate their current cookie consent.

My best guess at doing this is to change the "Name of the consent cookie" in the settings, therefore it won't exist for existing and re-prompt them for the cookie. Does that sound like the best approach?

Thanks.

**Comment by jellingsen** [comment]
Hi,

This is an interesting issue. While changing the cookie name would work, that seems very hacky. 

My suggestion would be a button in the admin panel that resets the consents. This could just be a hidden date field in the site settings, so when users visit the site we can check for consents that is given after that date.

**Comment by jellingsen** [comment]
Added button for invalidation. Feedback appreciated.
