### ISSUE TITLE
Not able to install plugin due to Craft primary key error.

### ISSUE THREAD

**Issue by mufi-siebird** [elleracompany/craft-cookie-consent#58]
Wen I tried to install plugin in latest craft cms site, it gives me below error:

```
[-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.005s). Output:
    > create table {{%cookie_consent_site_settings}} ...Exception: SQLSTATE[HY000]: General error: 3750 Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
The SQL being executed was: CREATE TABLE `cookie_consent_site_settings` (
	`site_id` int(11),
	`dateCreated` datetime(0) NOT NULL,
	`dateUpdated` datetime(0) NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0',
	`activated` tinyint(1) NOT NULL DEFAULT FALSE,
	`cssAssets` tinyint(1) NOT NULL DEFAULT TRUE,
	`jsAssets` tinyint(1) NOT NULL DEFAULT TRUE,
	`templateAsset` tinyint(1) NOT NULL DEFAULT TRUE,
	`showCheckboxes` tinyint(1) NOT NULL DEFAULT TRUE,
	`showAfterConsent` tinyint(1) NOT NULL DEFAULT TRUE,
	`cookieName` varchar(255) NOT NULL DEFAULT 'cookie-consent',
	`acceptAllButton` tinyint(1) NOT NULL DEFAULT FALSE,
	`headline` varchar(255) NOT NULL,
	`description` text,
	`template` varchar(255) NOT NULL,
	`refresh` tinyint(1) NOT NULL DEFAULT FALSE,
	`refresh_time` int(11) NOT NULL DEFAULT 500
) ENGINE=InnoDb DEFAULT CHARSET=utf8 (/var/www/dfn/mysite/htdocs/vendor/yiisoft/yii2/db/Schema.php:677)
```

I think this error comes because in your code, first table creates and then primary key assign. While creating table, primary key is not there so error comes and stop installation.

**Comment by jellingsen** [comment]
Hi,

That should not be an issue in it self, but I'm also unsure as to why it is added after the fact in that migration.

Are you on DigitalOcean by any chance? I've struggeled with this exact issue on another project where a compound primary key was required.

**Comment by mufi-siebird** [comment]
Yes. I am in digital ocean. Any code change while installation that adds primary key within installtion table?

**Comment by jellingsen** [comment]
Can you try to update composer and force the version `1.4.5-beta.1` (its a pre-release) and see if it installs and works correctly in your DO database?

**Comment by amici-infotech** [comment]
Hey, I dont think it will as the 2nd table also have the same setup that creates the table first and then assign primary key.

https://prnt.sc/xpo621

**Comment by mufi-siebird** [comment]
Hey, I dont think it will as the 2nd table also have the same setup that creates the table first and then assign primary key.

https://prnt.sc/xpo621

**Comment by jellingsen** [comment]
[release/1.4.5:src/migrations/Install.php](https://github.com/elleracompany/craft-cookie-consent/blob/release/1.4.5/src/migrations/Install.php) its updated in the pre-release.

**Comment by mufi-siebird** [comment]
Great! thanks. I will give it a shot and get back to you.

**Comment by jellingsen** [comment]
@mufi-siebird any updates here?

**Comment by mufi-siebird** [comment]
Hey @jellingsen looks like its working for me. Thanks

**Comment by jellingsen** [comment]
Perfect, thanks. v1.4.5 released.
