### ISSUE TITLE
Site settings - Show after Consent is displaying twice

### ISSUE THREAD

**Issue by kevinmu17** [elleracompany/craft-cookie-consent#60]
Duplicated settings, was just checking the plugin and noticed this ;)

**Comment by jellingsen** [comment]
Yeah, I've seen that. Thanks for reporting, ill make sure to remove it in the next update.

**Comment by mikewink** [comment]
Added a pull request for that along some other smaller changes. Hope it gets updated soon. :)

**Comment by jellingsen** [comment]
Fixed
