### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by BSBjorn** [elleracompany/craft-cookie-consent#63]
When installing the plugin for my site I encountered a error during installation. Composer install worked fine, but applying project config threw this error: `'ParseError: syntax error, unexpected ')''`  This only happened on my stage environment, not development. Different PHP versions (7.2.33 and 7.3.24)

`2021-02-23 13:46:19 [-][-][-][error][ParseError] ParseError: syntax error, unexpected ')' in /var/www/html/minkake-craft3/vendor/elleracompany/craft-cookie-consent/src/migrations/Install.php:95
Stack trace:
#0 /var/www/html/minkake-craft3/vendor/craftcms/cms/src/base/Plugin.php(138): craft\base\Plugin->createInstallMigration()
#1 /var/www/html/minkake-craft3/vendor/craftcms/cms/src/services/Plugins.php(527): craft\base\Plugin->install()
#2 /var/www/html/minkake-craft3/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(280): craft\services\Plugins->installPlugin('cookie-consent')
#3 /var/www/html/minkake-craft3/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(139): craft\console\controllers\ProjectConfigController->_installPlugins(Array)
#4 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#5 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('apply', Array)
#8 /var/www/html/minkake-craft3/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('apply', Array)
#9 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('apply', Array)
#10 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#11 /var/www/html/minkake-craft3/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('project-config/...', Array)
#12 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#13 /var/www/html/minkake-craft3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /var/www/html/minkake-craft3/craft(23): yii\base\Application->run()
#15 {main}`

Removing the `,` on line 94 resolved the issue for me.

**Comment by jellingsen** [comment]
Thank you for reporting. 

That looks like a typo, might be that some PHP versions are more forgiving.

**Comment by jellingsen** [comment]
Should be fixed now.
