### ISSUE TITLE
window object to read in JavaScript

### ISSUE THREAD

**Issue by kevinmu17** [elleracompany/craft-cookie-consent#65]
It would be nice to have a **window.ccc** object which contains all the choices for a consent or denial. So we can communicate outside a site (eq Google events)

For example:
```
if(window.ccc.default-marketing === 1){
       // communication to a service
}
```

**Comment by knynkwl** [comment]
+1

**Comment by kevinmu17** [comment]
Any update on this guys?

**Comment by sieir** [comment]
Sorry for the lack of response; spring's been/is very hectic for us. This shouldn't be that big of a feature to implement, however our current lack of time unfortunately pushes this more towards the summer at the earliest. 

If you needed this yesterday, we are more than happy to accept a pull request (given it works well and doesn't break anything), but between that (and a kudos in the release notes) I unfortunately can't promise anything or you an ETA at this time.
