### ISSUE TITLE
Change default template to use 'H3', instead of 'H1'

### ISSUE THREAD

**Issue by paulwaddington** [elleracompany/craft-cookie-consent#67]
Hello!

I know it's easy enough to create our own template, though I imagine there's people who are using the deafult. The problem is there shouldn't be more than one 'H1' tag on a page for SEO purposes and the default template adds a second 'H1'.

Thanks. Paul

**Comment by jellingsen** [comment]
Great feedback. Thanks, I'll get this included in the next update.
