### ISSUE TITLE
[Question] Blitz + Seomatic setup

### ISSUE THREAD

**Issue by umkasanki** [elleracompany/craft-cookie-consent#74]
Hello.

Could you clarify to set up the plugin correctly with Blitz and Seomatic?
In the docs you wrote:

> You will need to bust the SEOmatic cache in your twig templates (not in the SEOmatic script field)
> 
> {# -- START Cache-bust seomatic -- #}
> {% set scriptContainer = seomatic.script.container() %}
> {% do scriptContainer.clearCache(true) %}
> {# -- END Cache-bust seomatic -- #}

This snippet should be placed once or across whole site?
In the head?
Via ajax include [Using Blitz tag]?

Smth like this?
![изображение](https://user-images.githubusercontent.com/496132/136817023-1c63c17f-e07d-4a14-9e3f-bc69aef7646e.png)

Thanks

**Comment by johnwbaxter** [comment]
@umkasanki Did you ever work this one out?

**Comment by umkasanki** [comment]
@johnwbaxter 
Not yet.
But I would like to know or have an example of how it should be configured.

**Comment by johnwbaxter** [comment]
Well, I'll be trying out every option shortly so will let you know :)

**Comment by umkasanki** [comment]
Thanks @johnwbaxter

**Comment by jellingsen** [comment]
That snippet is for the internal SEOmatic cache mechanics, not related to blitz.

Have you seen the other Blitz-related issues? 
https://github.com/elleracompany/craft-cookie-consent/issues?q=is%3Aissue+is%3Aclosed+blitz

Did you manage to get it to work @johnwbaxter ?

**Comment by amici-infotech** [comment]
Hey. Did anyone make this work? I have seen other issues in github and make the consent banner working with blitz. But i am not able to stop SEOMatic scripts when consent is declided due to blitz cached page.
