### ISSUE TITLE
Can you enable translation for this too

### ISSUE THREAD

**Issue by wmdhosting** [elleracompany/craft-cookie-consent#77]
Can you enable us to translate this things too in CP / and end user will be able to change that if needed.. on multi lang sites..
![Snag_1a3c4154](https://user-images.githubusercontent.com/76176291/153026270-cacdcbc3-c495-4034-9eda-8da30f54266d.png)
![Snag_1a3d7dcb](https://user-images.githubusercontent.com/76176291/153026534-a50451a4-08ea-4739-9714-76ecf2700312.png)
![Snag_1a3d90b7](https://user-images.githubusercontent.com/76176291/153026548-e34fd027-74c6-4a8d-8936-7639b60e82f5.png)

**Comment by jellingsen** [comment]
These are already translatable with the built-in translation system as documented here: https://craftcms.com/docs/4.x/sites.html#provide-the-translations

Make a new folder called `translations` in the root folder of your project. Make another folder inside, with the language ID and then make a file called cookie-consent.php inside.

Check out the file in vendor/elleracompany/craft-cookie-consent/src/translations for an example.
