### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by MaximilianSchwarz** [elleracompany/craft-cookie-consent#8]
Hello,

i got the following error if i want to update to the version 1.2.2. It only works the version 1.2.0.0.

Can you assist me? I got the following error:
The requested package elleracompany/craft-cookie-consent 1.2.2 exists as elleracompany/craft-cookie-consent[1.0.0, 1.0.0.1, 1.0.0.2, 1.0.0.3, 1.1.0, 1.1.0.1, 1.2.0.0, dev-master] but these are rejected by your constraint.

**Comment by jellingsen** [comment]
I was able to reproduce when upgrading via composer. It does work via the admin panel, but packagist is not accepting “Craft” as a license setting and is stuck at v1.2.0.0. 

Working on a fix.

**Comment by MaximilianSchwarz** [comment]
Thanks :)

**Comment by jellingsen** [comment]
Released v1.2.3 now with the correct license and updated packagist. Please try upgrading to this version. Note that you might need to run `composer clear-cache`.

**Comment by MaximilianSchwarz** [comment]
Now it's work like a charm. Thanks for the support :)
