### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [elleracompany/craft-cookie-consent#80]
Will this plugin work with Craft 4?

**Comment by johnwbaxter** [comment]
I'll second this question!

**Comment by AndrewMac** [comment]
Please add me to the list of users wondering about this! :-)

**Comment by jellingsen** [comment]
It would surprise me if it just works!

I've been too busy lately to check and upgrade, I hope I'll get to it this week.

Its on my todo!

**Comment by mikewink** [comment]
Adding a bit of weight behind this ticket. :) We are using the plugin in many of our projects and would like to keep using it in Craft 4 too. Maybe we the users could help a bit with the upgrade if needed?

**Comment by wmdhosting** [comment]
+1

**Comment by jellingsen** [comment]
It is now updated. Please make an issue if you encounter any problems.

Sorry for the late update.
