### ISSUE TITLE
Problem with Craft Multisite

### ISSUE THREAD

**Issue by AndrewMac-UTS** [elleracompany/craft-cookie-consent#83]
I have multiple sites in my Craft 4 install, and although I can get to the main screen for the plugin settings, I cannot access any of the other screens. Clicking on them takes me to the dashboard instead. I can see that the URLs for the other plugin screens get mucked up by a siteURl parameter, like this:

https://craft4b.nitro/admin?site=craft4en/cookie-consent/site/craft4en

So it looks like those links need to be rearranged to move that siteUrl parameter to the end of the string. Ore perhaps remove it entirely? Not sure which, but it does look like they need to be changed.

Hope this isn't a big issue to fix! :-)

**Comment by jellingsen** [comment]
Hi! 

This should be resolved now in v4.0.1 - Please make a new issue should you find any more issues with the multisite routing.

Thanks for bringing this to my attention.

**Comment by AndrewMac-UTS** [comment]
And thanks to you for fixing this so quickly :-)
It seems to be working fine now! I do have one little suggestion, though, which I will pop into another ticket.
Cheers, Andrew
