### ISSUE TITLE
Switching between Craft sites

### ISSUE THREAD

**Issue by AndrewMac-UTS** [elleracompany/craft-cookie-consent#85]
Hi there, this is not a bug, just a suggestion …
I have multiple sites installed (Craft 4 Pro), and when I switch between sites I always end up back at the Read Me page. It would save a lot of time, and be much more efficient, if we could stay on the same screen when switching sites. For example, if I'm on the "Site Settings" page I'd like to say on that page when I switch to another site, not go to the Read Me page.
Thanks for listening, and hopefully considering this change.
Cheers, Andrew

**Comment by jellingsen** [comment]
Added a fix for this in v4.0.3.

**Comment by AndrewMac-UTS** [comment]
Thanks so much!
Cheers, Andrew
