### ISSUE TITLE
[Craft 4] Unable to add/reorder/delete table rows

### ISSUE THREAD

**Issue by WHITE-developer** [elleracompany/craft-cookie-consent#90]
Since Craft 4 the defaults for editable tables changed. https://github.com/craftcms/cms/commit/1b197ef7c6425f59544b9097f8339beeea9de771
`allowAdd`, `allowReorder` and `allowDelete` are now default false, so should be added here https://github.com/elleracompany/craft-cookie-consent/blob/master/src/templates/settings/_includes/group.twig#L100

**Comment by peerfischer** [comment]
Will there be an update?

**Comment by mikewink** [comment]
@WHITE-developer thank you very much for the debugging. I created a PR https://github.com/elleracompany/craft-cookie-consent/pull/93 for your fix.

Lets hope it will be reviewed soon. Your solution works well for me.

**Comment by jellingsen** [comment]
Thank you so much for the debugging @WHITE-developer and for the PR @mikewink !

And I applogize for the slow response to this.

I've released v4.0.4 with this fix.

**Comment by WHITE-developer** [comment]
@jellingsen Thanks for the fix, but looks like the updates isn't pushed to packagist? Could you update it their also?

**Comment by jellingsen** [comment]
@WHITE-developer my applogies! Should be updated now.
