### ISSUE TITLE
No field to add detailed cookie information for custom cookie group

### ISSUE THREAD

**Issue by peerfischer** [elleracompany/craft-cookie-consent#91]
There is no field in backend to enter detailed cookie information  (like decription, lifetime aso).

**Comment by mikewink** [comment]
I have the same problem with the latest version of the plugin in Craft 4. I can create new cookie groups, but the form field to enter cookies is not visible. Old cookie definitions from before the Craft 4 update are still visible, but do not allow adding new cookie information!

**Comment by jellingsen** [comment]
@mikewink your PR is merged and released in v4.0.4.

Thank you!
