### ISSUE TITLE
Forbidden Cookies don't disappear

### ISSUE THREAD

**Issue by Sikatrih** [elleracompany/craft-cookie-consent#97]
Hi! I am filling up the table with cookies inside the cookie groups in admin panel. 
 
![_⚙ Statistikk - Norsk Folkehjelp](https://user-images.githubusercontent.com/7059095/194273717-d9ef3bb8-e6ab-47e9-8415-0d22d289b932.png)

But this cookies don't disappear when I forbidding the group. 

![_ Norsk Folkehjelp _ Forside](https://user-images.githubusercontent.com/7059095/194274440-f7424329-bd77-4780-9f1e-b6cc27e91799.png)

I added {% hook 'after-body-start' %} after body. What I could miss? Or is it expected behavior?

**Comment by Humbi1992** [comment]
+1

**Comment by jellingsen** [comment]
The plugin does not implement cookie blocking, this is something you need to manage yourself based on the choices the visitor makes.
